sudo: required
language: java
jdk: openjdk11

services:
  - docker
   
script:
  - mvn clean install -f ./book-service/pom.xml  -B

after_success:
  - docker build -t aayush4v/book-service -f ./book-service/Dockerfile ./book-service  