sudo: required
language: java
jdk: openjdk11

services:
  - docker
 
script:
  - ./book-service/mvnw clean install -B

after_success:
  - docker build -t aayush4v/book-service -f ./book-service/Dockerfile ./book-service  